import type { Config } from "jest";

const config: Config = {
	preset: "ts-jest",
	testEnvironment: "node",
	rootDir: "src",
	moduleFileExtensions: ["ts", "js", "json"],
	testMatch: ["**/*.test.ts", "**/*.spec.ts"],
	collectCoverageFrom: [
		"**/*.ts",
		"!**/*.test.ts",
		"!**/*.spec.ts",
		"!**/types/**",
		// Generated by `prisma generate`, and rewritten on every schema change.
		"!**/generated/**",
	],
	coverageDirectory: "../coverage",
	// One database, and every suite truncates it between tests: two workers
	// empty each other's rows mid-test, which surfaces as a spray of unrelated
	// 401s that all pass when the file is run alone. Serial is the price of
	// testing against a real Postgres; per-worker schemas are the way out if
	// the run ever gets slow.
	maxWorkers: 1,
	setupFiles: ["<rootDir>/test/env.ts"],
	setupFilesAfterEnv: ["<rootDir>/test/setup.ts"],
	moduleNameMapper: {
		"^@/(.*)$": "<rootDir>/$1",
		"^(\\.{1,2}/.*)\\.js$": "$1",
	},
};

export default config;
