CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(32)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(254) NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- The service lowercases and trims both before writing, so these constraints
    -- reject "Alice@example.com" once "alice@example.com" exists. The handler
    -- maps each name to its own 409 code, so do not rename them casually.
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email)
);
